name: build our image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Install Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build and push
        run: |
          docker buildx build --push \
            --tag "${{secrets.DOCKERHUB_USER}}/memgame:${GITHUB_SHA::8}" \
            --tag "${{secrets.DOCKERHUB_USER}}/memgame:latest" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
